### ISSUE TITLE
完全仿微信Demo 选择图片页面bug

### ISSUE THREAD

**Issue by ImSevenEleven** [CysionLiu/ImagePicker#10]
点击+号弹出菜单之后，选择拍照，可以选择拍还是直接返回，不过这个问题这两种情况都会存在。
问题：再次点击+号 选择相册，然后弹出选择相册页面title栏 btnOK不显示，图片上选择框也不显示..

**Comment by CysionLiu** [comment]
手头5个机子未复现。

**Comment by ImSevenEleven** [comment]
好吧，我用的米8测试的，不存在的话就关了吧，再有人提再说吧。

**Comment by ImSevenEleven** [comment]
或者你加下我QQ  1563206679  我可以录屏给你

**Comment by CysionLiu** [comment]
又找了个机子测试了下，的确存在问题，是我之前测试操作有点问题。这个不影响lib使用，写demo的时候少加了多选模式，已提交。谢谢提出

**Comment by ImSevenEleven** [comment]
ok fine :-)
