### ISSUE TITLE
关于自定义固定比例问题

### ISSUE THREAD

**Issue by JackHang** [CysionLiu/ImagePicker#12]
首先说明：我说的自定义比例是自定义固定比例，不是FREE模式下的用户随意变更的比例
新的FreeCrop内有CUSTOM的参数，但是想要自定义宽高比必须重写裁剪的类。为什么不判断当我传的CropMode是CUSTOM的时候，就调取FocusWidth和FocusHeight的宽高比呢？

**Comment by CysionLiu** [comment]
想法挺好，之后会考虑增加
