### ISSUE TITLE
拍照裁剪出现问题

### ISSUE THREAD

**Issue by xmmdream** [CysionLiu/ImagePicker#18]
1.先选择相册里面的一张图片，进入到裁剪页面，点击返回到相册列表
2.再拍照确认后，自动调整到裁剪图片页面
3.此时展示裁剪图片，还是之前选择相册里面选择的那张，不是刚才拍照的图片

**Comment by Bter** [comment]
我的也是

**Comment by CysionLiu** [comment]
1.0.7版本解决

**Comment by Bter** [comment]
good
