### ISSUE TITLE
希望能集成 Luban 或 AiYaCompressHelper 压缩算法

### ISSUE THREAD

**Issue by lovelyelfpop** [CysionLiu/ImagePicker#2]
https://github.com/Curzibn/Luban
https://github.com/nanchen2251/AiYaCompressHelper

**Comment by CysionLiu** [comment]
调用的上层，可能不只选择9张图片，还可能再次进入选择或者修改，若是在此lib中压缩，会耦合较多。另外，既然选择的图片集合都有了，上层单独集成个压缩库，都有链式调用的方法，一步压缩到位，不算麻烦
