### ISSUE TITLE
java.lang.NullPointerException 这个错误没人遇到过？

### ISSUE THREAD

**Issue by scwang90** [CysionLiu/ImagePicker#21]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.szysky.customize.siv.SImageView.getTag()' on a null object reference at com.szysky.customize.siv.ImageLoader$2.handleMessage(ImageLoader.java:475)

版本：

    api 'com.cysion:ImagePicker:1.0.7'

**Comment by CysionLiu** [comment]
看报错不是在lib内部啊
