### ISSUE TITLE
目前拍照的照片保存的是系统相册，我想保存到指定文件夹怎么处理？

### ISSUE THREAD

**Issue by zengss** [CysionLiu/ImagePicker#32]
我研究了微信朋友圈拍照后的照片都是保存到腾讯文件夹

**Comment by CysionLiu** [comment]
android Q以后对存储框架进一步进行了限制。目前看来，提供指定文件夹不是太好的选择

**Comment by CodeIdeal** [comment]
其实这点我觉得应该作为一个可配置参数提供给开发者，应为如果只是用来裁剪导入图像这样一个临时行为的话，保存到系统相册的话，用户体验很不好，每导入一次图片都会生成一张对用户无用的图片在相册里，有的用户会很反感这样的到处扔垃圾的行为。如果你也同意我可以把相关代码提个pull request

**Comment by CysionLiu** [comment]
裁剪图片位置已经改成可配置；若仅是拍照的话，本库就是调用了系统照相机app进行拍照，存储在相册应属合理，不提供改动。
