### ISSUE TITLE
设置裁剪框宽高后 在自由裁剪模式没有用

### ISSUE THREAD

**Issue by Mangosir** [CysionLiu/ImagePicker#33]
设置裁剪框宽高后 在自由裁剪模式没有用

**Comment by CysionLiu** [comment]
设置宽高和输出宽高，仅对普通裁剪管用，这也伴随这裁剪后的图片尺寸缩放；自由裁剪会保持原图对应范围内的宽高，不会有压缩和尺寸调整操作
