### ISSUE TITLE
Android 10 不能加载本地图片。

### ISSUE THREAD

**Issue by JustinChiang123** [CysionLiu/ImagePicker#36]
解决办法参看https://juejin.im/post/5d80ef726fb9a06aeb10f223，ImageLoader 可以自己修改，但是，FreeCropActivity等其他类里面的，还希望作者修改修改， mSourceUri = Uri.fromFile(new File(mImagePath)); Android 10 是不能正确加载的。

**Comment by lovelyelfpop** [comment]
这链接里面，把文件路径转为 content uri，不太靠谱啊。Android Q 上非沙箱目录的图片，应该是得不到真实路径的吧。给 glide、luban 等使用之前，应该2种方案：
1、选图时得到图片的 content uri，而非 file:// 或 path
2、选图时，将图片复制到沙箱目录下，得到 file:// 或 path

**Comment by CysionLiu** [comment]
几位的项目targetsdk都设置到29了吗？tsdk<29情况下，模拟器和华为EMUI10没有发现此问题

**Comment by lovelyelfpop** [comment]
早晚都要升，晚改不如早改啊。

**Comment by kingiis** [comment]
10.0就是万剑归宗了，浪子回头了

**Comment by CysionLiu** [comment]
参考1.0.9.Q版本
