### ISSUE TITLE
能否单独配置图片数量限制等信息？

### ISSUE THREAD

**Issue by jdhdevelop** [CysionLiu/ImagePicker#39]
你好，请问是否可以实现，比如我在不同的地方使用，可以单独配置不同的图片限制数量。

**Comment by CysionLiu** [comment]
在不同的地方使用，可在对应的地方配置ImagePicker

**Comment by jdhdevelop** [comment]
你好，ImagePicker不是单例模式吗？如何能有不同的配置呢？

**Comment by CysionLiu** [comment]
imagepicker虽是单例，但也仅是针对该对象而言，而并不局限其属性是否变化。比如图片数量限制，每次在不同的地方调用，即可通过setSelectLimit方法来设置本次调用的限制数量。

**Comment by jdhdevelop** [comment]
好的，谢谢。
