### ISSUE TITLE
直接start ImageGridActivity会报错SuperCheckBox.setChecked(boolean) 为空 1.0.9.Q

### ISSUE THREAD

**Issue by SHUCHAOLIN** [CysionLiu/ImagePicker#40]

**Comment by CysionLiu** [comment]
复现不了，请贴代码或者bug日志

**Comment by SHUCHAOLIN** [comment]
不知道啊&nbsp; 我刚才依赖1.0.9.q的时候直接依赖不了了&nbsp;



---原始邮件---
发件人: "Cysion Liu"<notifications@github.com&gt;
发送时间: 2019年12月9日(星期一) 上午9:39
收件人: "CysionLiu/ImagePicker"<ImagePicker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"SHUCHAOLIN"<1848761791@qq.com&gt;;
主题: Re: [CysionLiu/ImagePicker] 直接start ImageGridActivity会报错SuperCheckBox.setChecked(boolean) 为空 1.0.9.Q (#40)



复现不了，请贴代码或者bug日志

**Comment by SHUCHAOLIN** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yjlc.imtogether/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lzy.imagepicker.view.SuperCheckBox.setChecked(boolean)' on a null object reference
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.os.Handler.dispatchMessage(Handler.java:107)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.os.Looper.loop(Looper.java:214)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread.main(ActivityThread.java:7356)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at java.lang.reflect.Method.invoke(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
&nbsp;&nbsp;&nbsp;&nbsp; Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lzy.imagepicker.view.SuperCheckBox.setChecked(boolean)' on a null object reference
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at com.lzy.imagepicker.ui.ImageGridActivity.onCreate(ImageGridActivity.java:121)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.Activity.performCreate(Activity.java:7802)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.Activity.performCreate(Activity.java:7791)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.os.Handler.dispatchMessage(Handler.java:107)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.os.Looper.loop(Looper.java:214)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at android.app.ActivityThread.main(ActivityThread.java:7356)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at java.lang.reflect.Method.invoke(Native Method)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)&nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Cysion Liu"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月9日(星期一) 上午9:39
 收件人:&nbsp;"CysionLiu/ImagePicker"<ImagePicker@noreply.github.com&gt;;
 抄送:&nbsp;"￡嘿嘿丨有点坏ღღღ"<1848761791@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [CysionLiu/ImagePicker] 直接start ImageGridActivity会报错SuperCheckBox.setChecked(boolean) 为空 1.0.9.Q (#40)

 

 
复现不了，请贴代码或者bug日志

**Comment by CysionLiu** [comment]
新开了项目，还是复现不了；是否资源文件被覆盖了？是否调用没按说明来？
