### ISSUE TITLE
裁剪页面，状态栏和TopBar重叠

### ISSUE THREAD

**Issue by Christain** [CysionLiu/ImagePicker#41]
系统：Android 9
库版本：1.2.0
裁剪页面，状态栏和TopBar重叠

**Comment by CysionLiu** [comment]
2个手机测试了下，没有复现；两种裁剪方式都会出现吗？是否还有别的手机测过？

**Comment by Christain** [comment]
小米的MIUI11和华为EMUI9.1.0都有这个问题，只用了固定比例的裁剪。看了源码发现是在baseactivity统一处理的，也很奇怪为啥只有剪裁页面有问题。
            ImagePicker instance = ImagePicker.getInstance();
            instance.setImageLoader(new GlideImageLoader());
            instance.setShowCamera(true);
            instance.setCrop(true);
            instance.setMultiMode(false);
            instance.setSaveRectangle(true);
            instance.setFocusWidth(PhoneUtil.getScreenWidth(getActivity()) * 3 / 4);
            instance.setFocusHeight(instance.getFocusWidth());
            File cropFile = new File(PhoneUtil.getAppRootPath(getActivity()) + "/cropTemp");
            if (!cropFile.exists()) {
                cropFile.mkdirs();
            }
            instance.setCropCacheFolder(cropFile);
            instance.setOutPutX(800);
            instance.setOutPutY(800);

            Intent intent = new Intent(getActivity(), ImageGridActivity.class);
            startActivityForResult(intent, PICTURE);
