### ISSUE TITLE
期望新增功能~请查看~

### ISSUE THREAD

**Issue by 1017161726** [CysionLiu/ImagePicker#45]
选中图片时，目前是打勾，是否考虑添加阿拉伯数字排序呢。
选中图片时，能有一个自定义的限制集吗？目前只有数量超限有校验，
可以新增，文件大小校验，图片后缀格式校验，尺寸校验等，返回是否允许选中。
目前的项目中 如果不使用裁剪，好像还没有图片压缩。

**Comment by CysionLiu** [comment]
多谢建议
