### ISSUE TITLE
你好，请问适配AndroidQ版本

### ISSUE THREAD

**Issue by xiaojidonggong** [CysionLiu/ImagePicker#50]
com.cysion:ImagePicker:1.2.0.Q
引用这个适配了AndroidX 了么

**Comment by xiaojidonggong** [comment]
为什么，我用华为荣耀20，系统版本Android10
打开相册功能，里面一片黑，没有显示相册里的照片呢？原因是？

**Comment by CysionLiu** [comment]
tagetsdk>=29，必须用1.2.0.Q；荣耀20测过没出现你那问题
