### ISSUE TITLE
注释乱码

### ISSUE THREAD

**Issue by JanRisun** [CysionLiu/ImagePicker#53]
![image](https://user-images.githubusercontent.com/37615305/78335735-c48d8100-75c0-11ea-8599-157c0a3fb095.png)

**Comment by JanRisun** [comment]
感谢适配，感谢分享

**Comment by CysionLiu** [comment]
乱码出现在挺早以前了，没能恢复，在androidX版本删除了很多乱码注释。不是ide的问题。
