### ISSUE TITLE
华为P30出现崩溃情况

### ISSUE THREAD

**Issue by zuojianjian** [CysionLiu/ImagePicker#55]
#89508 java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:129)
![image](https://user-images.githubusercontent.com/20851340/78740174-a3de7600-7988-11ea-80d6-f929b375e9c4.png)

**Comment by zuojianjian** [comment]
![WechatIMG5561](https://user-images.githubusercontent.com/20851340/82289066-7f89a680-99d6-11ea-90ba-2b171d076649.png)
这个问题无解吗？这个是又有用户直接打电话反馈的，让他提供的崩溃截图android10 华为荣耀9

**Comment by zuojianjian** [comment]
使用的androidX版本

**Comment by CysionLiu** [comment]
1.2.0.x :是不会出现这个bug的。1.2.0.Q，是为了targetSdk>=29来做的，目前demo在华为  emui 9.0,9.1,10.0,10.1平台，荣耀magic3.0版本上都测试过，并未出现上述问题。
