### ISSUE TITLE
一加手机 Android10 图片列表显示图片都是黑色的

### ISSUE THREAD

**Issue by TianTingting** [CysionLiu/ImagePicker#57]
/storage/emulated/0/ Pictures/Screenshots/
Screenshot 20200324-070146.jpg: open failed: EACCES (Permission denied)

**Comment by TianTingting** [comment]
迁移androidx,图片列表都是黑色的
/storage/emulated/0/ Pictures/Screenshots/
Screenshot 20200324-070146.jpg: open failed: EACCES (Permission denied)

**Comment by CysionLiu** [comment]
安卓10且用了androidx ,需要api 'com.cysion:ImagePicker:1.2.0.Q'；若没有用到androidx，则没适配安卓10

**Comment by TianTingting** [comment]
如果需要直接导入model呢？
