### ISSUE TITLE
Q版本返回的uri 使用起来不太方便啊

### ISSUE THREAD

**Issue by DuShuYuan** [CysionLiu/ImagePicker#58]
选择图片上传要压缩的  要先转成file，uri直转file的方法不适合这里的情况，只能先uri转InputStream，然后再写入本地文件，读取file再去压缩，很麻烦啊

请问还有没有其他的方法

`
ArrayList<ImageItem> images = (ArrayList<ImageItem>) data.getSerializableExtra(ImagePicker.EXTRA_RESULT_ITEMS);
                List<File> files = new ArrayList<>();
                for (int i = 0; i < images.size(); i++) {
                    try {
                        
String path = PathUtils.getExternalAppCachePath() + File.separator + images.get(i).uri.hashCode() + ".jpg";
                        
File file=new File(path);
                        FileIOUtils.writeFileFromIS(file,getContentResolver().openInputStream(images.get(i).uri));
                        files.add(file);
                    } catch (FileNotFoundException e) {
                        e.printStackTrace();
                    }
                }
                Luban.compress(this, files)
`

**Comment by CysionLiu** [comment]
tagetsdk>=29以后，仅支持uri访问文件的内容

**Comment by is1988** [comment]
确实是这样，有点麻烦，我也做了一层转换，适配android Q，是因为android 10以上用户看不到相册，只显示缩略图
