### ISSUE TITLE
华为部分最新型号手机使用android10大范围出现上传图片出现崩溃问题

### ISSUE THREAD

**Issue by zuojianjian** [CysionLiu/ImagePicker#63]
![WechatIMG5561](https://user-images.githubusercontent.com/20851340/82551822-84478980-9b93-11ea-9dc6-ceda097e3fa8.png)
今天一天六个投诉电话都是华为最新型号手机都是同一个错误，上传图片崩溃问题，恳请大佬看看底层出现什么问题了

**Comment by zuojianjian** [comment]
![WechatIMG5561](https://user-images.githubusercontent.com/20851340/82552000-e1dbd600-9b93-11ea-85e7-7c312cc0bdb0.png)

**Comment by zuojianjian** [comment]
target=29 
api 'com.cysion:ImagePicker:1.2.0.Q'
所有崩溃用户都是android 10 且是华为手机，小米10没有问题

**Comment by CysionLiu** [comment]
Q版本，访问文件，比如上传文件，常见的有两种方式，一个是根据uri获得流，一是复制文件到专有存储空间，然后进行传统方式访问文件。根据你的反馈，用户应该是能正常选择图片的，也就是uri是能拿到的。至于上传出问题，我这边目前也仅能提供上述意见。

**Comment by CysionLiu** [comment]
我这边emui 9.0,9.1,10.0,10.1，还有magic 3.0都测过，demo都是没有这个bug的。不过库里相应代码的确存在空指针的风险，刚发布了1.2.1.Q版本，希望能帮到你。
